### ISSUE TITLE
About lidar

### ISSUE THREAD

**Issue by Ethan0207** [reiniscimurs/DRL-robot-navigation#124]
Hi,
This project uses a single-line Lidar. I would like to ask if multi-line Lidar is feasible.

**Comment by reiniscimurs** [comment]
Hi,

This project uses multi-channel Lidar. We squash the 3D measurements into 2D to create a single dimensional vector for input into the TD3 network. Direct multi-channel input is also possible in theory. But this project does not support that. Here, only single dimension inputs are supported out of the box.

**Comment by Ethan0207** [comment]
OK, thank you for your reply.  It is helpful for me.

**Comment by Ethan0207** [comment]
Hi，
These days I changed the lidar. But I met a problem. The lidar had changed successfully, but the car model could not move. I checked my plugin and I synced my robot namespace. Could you give me some suggestions?
![3 20-1](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/43b98a6a-278d-44f5-9721-33d3acfa903a)
![3 20-2](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/58957f51-c1a1-4aa8-9ecb-a2aaa7077d44)
![3 20-3](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/12cb25b1-eb30-4aaf-9adb-f8f8de462788)
![3 20-4](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/b2ba018f-1e7e-4b08-81ba-35ae36491ce5)
this is my modified env.py file.
![3 20-5](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/f7a62e72-054b-40e6-85b9-f93bacd45510)
![3 20-6](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/3161799b-8d71-47c6-ba83-9b2b58e35f06)
![3 20-7](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/5b12575b-730c-4734-afad-813cf7eb8442)
this is main xacro file.
![3 20-8](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/0ae92a76-d590-49ba-8b4f-cd0909229af1)
![3 20-9](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/4ae7d16d-b421-4e6c-84a8-22e50d1b6213)
![3 20-10](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/3e38d569-6758-42a2-9ebc-9095b4f891af)
![3 20-11](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/b1489514-f9d2-45b5-87ae-1b6d2902f8c7)
![3 20-12](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/f5700f1c-a20f-4f2a-95aa-fddd39a3444e)
![3 20-13](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/5d20b2f3-e6af-4927-a0fb-6bf6751b47a0)
![3 20-14](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/00d468bd-4f72-4445-b0e2-5062064046f8)
![3 20-15](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/f11d7099-4577-4dbe-8623-dcd7456b8a18)
![3 20-17](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/bb83ae85-1294-4a35-b818-684b8ad56348)
this is main plugin file
![3 20-18](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/ee203696-1e23-496f-9552-ff5131442ba2)

**Comment by reiniscimurs** [comment]
Hi,

Please provide more information about the issue. What do you mean it cannot move? Is there an error or does the network not produce an output?
How have you debugged the code? How do you check that the data from your lidar is correct?

Quick note is that in your callback you are using a point_cloud2 function but your message type is PointCloud instead of PointCloud2. But in general, these kinds of changes are outside the scope of this repository and I would not have the time to investigate such in depth changes. Good luck!

**Comment by Ethan0207** [comment]
Hi，
Thank you for your reply. Firstly, the model can not move. It just means when I trained it, nothing happened. But the topic could be subscribed, so I guessed the  problem is with the car motion plugin. Therefore, I checked it and I synced my robot namespace. But now, I find a strange thing. When I change my robot namespace to "/", it is normal and the model can move. I adjusted the namespace earlier because it reported the following error.
**Traceback (most recent call last):
  File "train_velodyne_td3.py", line 346, in <module>
    next_state, reward, done, target = env.step(a_in)
  File "/home/team/DRL-robot-navigation-scout/TD3/velodyne_env.py", line 196, in step
    self.odom_x = self.last_odom.pose.pose.position.x
AttributeError: 'NoneType' object has no attribute 'pose'**
So I synced my robot namespace from"/" to "/scout". Now, I adjust the namespace to "/". It is normal.
Secondly, based on your answer, if I want to check if it has an output, how can I do?
Finally, about the lidar, it is good suggestion, I will try to synced the message type.

**Comment by Ethan0207** [comment]
Add:
I synced my robot namespace from"/" to "/scout". It is ok. But the model can not move. Based on your answer, if I want to check if it has an output, how can I do? Could you give me some suggestions?

> Hi， Thank you for your reply. Firstly, the model can not move. It just means when I trained it, nothing happened. But the topic could be subscribed, so I guessed the problem is with the car motion plugin. Therefore, I checked it and I synced my robot namespace. But now, I find a strange thing. When I change my robot namespace to "/", it is normal and the model can move. I adjusted the namespace earlier because it reported the following error. **Traceback (most recent call last): File "train_velodyne_td3.py", line 346, in next_state, reward, done, target = env.step(a_in) File "/home/team/DRL-robot-navigation-scout/TD3/velodyne_env.py", line 196, in step self.odom_x = self.last_odom.pose.pose.position.x AttributeError: 'NoneType' object has no attribute 'pose'** So I synced my robot namespace from"/" to "/scout". Now, I adjust the namespace to "/". It is normal. Secondly, based on your answer, if I want to check if it has an output, how can I do? Finally, about the lidar, it is good suggestion, I will try to synced the message type.

**Comment by tina525241** [comment]
> Hi， I unified the sensor_msgs/PointCloud, but it still reported the following error. **Traceback (most recent call last): File "train_velodyne_td3.py", line 346, in next_state, reward, done, target = env.step(a_in) File "/home/team/DRL-robot-navigation-scout/TD3/velodyne_env.py", line 196, in step self.odom_x = self.last_odom.pose.pose.position.x AttributeError: 'NoneType' object has no attribute 'pose'** I didn't understand this error. Can you help me explain it? And faced with such mistakes, how to solve?

Hi! Just fixed this problem and found someone has encountered the same problem. In velodyne_env.py there's a "self.last_odom" which is init with "None", if you change "self.last_odom = None" into "self.last_odom = Odometry()" the attribute error will be solved. (At least for me) 
:)

**Comment by Ethan0207** [comment]
> > Hi， I unified the sensor_msgs/PointCloud, but it still reported the following error. **Traceback (most recent call last): File "train_velodyne_td3.py", line 346, in next_state, reward, done, target = env.step(a_in) File "/home/team/DRL-robot-navigation-scout/TD3/velodyne_env.py", line 196, in step self.odom_x = self.last_odom.pose.pose.position.x AttributeError: 'NoneType' object has no attribute 'pose'** I didn't understand this error. Can you help me explain it? And faced with such mistakes, how to solve?
> 
> Hi! Just fixed this problem and found someone has encountered the same problem. In velodyne_env.py there's a "self.last_odom" which is init with "None", if you change "self.last_odom = None" into "self.last_odom = Odometry()" the attribute error will be solved. (At least for me) :)

Hi, thank you for your reply. I have solved the problem. Could you tell me what the reason is？

**Comment by reiniscimurs** [comment]
Hi,

Initializing with Odometry() will solve the symptom but not the issue. The reason why this error appears is that there has been no odometry published to the topic that you subscribed to. So the callback does not get triggered and value for `self.last_odom` does not get updated before you call it. We initialize with `None` so that we accidentally would not be using some random values in odometry that would be difficult to trace. If you initialize with `Odometry()` you will get some input already in `self.last_odom` from the very beginning with some dummy numbers, but if the odometry callback will never be triggered, your `self.last_odom` will never be updated and the odoetry information will be wrong.

I assume this issue arises for you because of one of two reasons:
1. Odometry simply has not started publishing yet in which case you can try increasing the wait time for ros to settle here: https://github.com/reiniscimurs/DRL-robot-navigation/blob/main/TD3/train_velodyne_td3.py#L253
2. The topic you are subscribing to is either wrong or not publishing anything. You should check your published topics, their names and use `rostopic echo` to see their values. For instance, you are hardcoding a prefix /scout to some topics in your plugin but not for odom. But you still have prefix /odom in your odometry subscriber. I would suggest double checking that.

**Comment by Ethan0207** [comment]
Hi，
Thank you for your reply. It is extremely helpful for me. I have another question. 
![3 29](https://github.com/reiniscimurs/DRL-robot-navigation/assets/138771150/635153be-6374-4457-a169-45faeea2264d)
From this picture, I can't understand how to  setting the filtering parameter? For example, the filtering parameter of Turtlebot waffle is -0.072. How did you calculate 0.072?

**Comment by reiniscimurs** [comment]
It is simply the height from the ground at which you have set your sensor (plus some buffer value)
